apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-commissioning-webapp
spec: 
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  - name: frontend
    image: procosys.azurecr.io/procosys/comm-webapp:{imageTagName}
    ports:
    - name: http
      port: 5000
    publicPort: http
    secrets:
    - auth
    - appInsights
    environmentConfig:
    # Development environment
    - environment: dev
      identity:
        azure:
          clientId: fb57fb35-f927-4271-9976-342070cb9f54
      imageTagName: latest  
      variables:
        procosysWebApi: '{"baseUrl":"https://pcs-main-api-dev.azurewebsites.net/api","apiVersion":"&api-version=4.1","scope":["api://dd38f169-bccf-4d0e-a4ad-d830893cfa75/web_api"]}'
        ocrFunctionEndpoint: 'https://pcs-mc-webapp-non-prod-funcs.azurewebsites.net/api/pcs_ocr?'
        authSettingsEndpoint: 'https://pcs-config-non-prod-func.azurewebsites.net/api/CommWebApp/Auth?'
      monitoring: true
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'      
    - environment: test
      identity:
        azure:
          clientId: 88ea24df-ef2a-4f85-b9c0-dfb7ddffd4e3
      variables:
        procosysWebApi: '{"baseUrl":"https://pcs-main-api-dev.azurewebsites.net/api","apiVersion":"&api-version=4.1","scope":["api://dd38f169-bccf-4d0e-a4ad-d830893cfa75/web_api"]}'
        ocrFunctionEndpoint: 'https://pcs-mc-webapp-non-prod-funcs.azurewebsites.net/api/pcs_ocr?'
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'      
    - environment: prod
      identity:
        azure:
          clientId: 76c09c7d-9570-4920-a2b3-87dabc06447f
      variables:
        procosysWebApi: '{"baseUrl":"https://pcs-main-api-dev.azurewebsites.net/api","apiVersion":"&api-version=4.1","scope":["api://dd38f169-bccf-4d0e-a4ad-d830893cfa75/web_api"]}'
        ocrFunctionEndpoint: 'https://pcs-mc-webapp-non-prod-funcs.azurewebsites.net/api/pcs_ocr?'
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'      
  privateImageHubs:
    procosys.azurecr.io:
      username: 9d3898e4-730f-4fb5-8ddf-a5de51537896
      email: arbje@equinor.com

