apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-commissioning-webapp
spec: 
  environments:
  - name: dev
  - name: test
  - name: prod

  components:
  - name: frontend
    ports:
    - name: http
      port: 5000
    publicPort: http
    environmentConfig:
    - environment: prod
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'
  dnsExternalAlias:
    - alias: apps.procosys.equinor.com
      component: frontend
      environment: prod
      useCertificateAutomation: true

