trigger:
  branches:
    include:
    - main
    - dev

resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-infra
    endpoint: 'procosys - github'

Global variables for the pipeline
variables:
 - template: templates/variables/procosys-global-variables.yml@templates
 - template: templates/variables/comm-webapp-variables.yml@templates

 - name: 'repositoryName'
   value: procosys/comm-webapp

stages:
build_and_test stage. Yarn test, Docker build, tag and push
- stage: build_and_test
  displayName: 'Build & Test'
  variables:
    envName: 'build_and_test'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    containerRegistry: '${{ variables.containerRegistryName }}'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    dockerfilePath: '/.docker/Dockerfile'
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'

  jobs:
  - template: /templates/pipelines/dockerbuild-comm-webapp.yml@templates
    parameters:
      deploymentName: 'docker_build_push'
      dependsOn: ''
      envGroup: '${{ variables.envGroupName }}'
      dockerfilePath: '${{ variables.dockerfilePath }}'
      buildContext: '$(Build.SourcesDirectory)'
      repository: '${{ variables.repositoryName }}'
      dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'

# Deploy to dev environment
- stage: dev
  displayName: 'Deploy to dev'
  dependsOn: 'build_and_test'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  variables:
    envName: 'dev'
    envRg: '${{ variables.envRgName }}'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    containerRegistry: '${{ variables.containerRegistryName }}'

  jobs:
  - template: /templates/pipelines/kubernetes/comm-webapp-deploy.yml@templates
    parameters:
      deploymentName: 'deploy_to_k8s'
      dependsOn: ''
      serviceConnection: '${{ variables.serviceConnection }}'
      env: '${{ variables.envName }}'
      envRg: '${{ variables.aksRgName }}'
      envGroup: '${{ variables.envGroupName }}'
      dockerImage: '${{ variables.containerRegistry }}.azurecr.io/${{ variables.repositoryName }}:$(Build.BuildId)'
      clusterName: '${{ variables.aksTestName }}'